### ISSUE TITLE
InstructorFeedbackEditPageUiTest: consolidate similar helper methods

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5802]
The test currently has many similar helpers methods like `clickVisibilityOptionsForQuestion1()`, `clickVisibilityOptions(questionNumber)`, and `clickVisibilityOptionsForNewQuestion()`

Actually only the second form is needed.

**Comment by sujeet14108** [comment]
Would take it

**Comment by sujeet14108** [comment]
@YongJieYongJie @damithc 
I am not able to find above methods i guess it may have been solved but there are other similar methods like `clickquestionSaveForQuestion1()` and `clickQuestionEditForQuestion1` which need to be removed

**Comment by damithc** [comment]
@TEAMMATES/activedevs can someone confirm?

**Comment by chowyb** [comment]
@damithc @sujeet14108 
The method mentioned in the issue was removed in #5939, although other similar methods still exist in the file. Leaving the `NewQuestion` methods as a separate method appears to be a conscious decision in #6473, therefore it is likely that only the `Question1` methods need to be removed.

@whipermr5 might want to provide additional info here as he was working on #6473.

**Comment by whipermr5** [comment]
Yes, what @chowyb said. The `*ForNewQuestion` methods are needed as the tests shouldn't have to know that the question number for the new question is `-1` - that is an implementation detail that should only be known to the `PageObject`s.

**Comment by sujeet14108** [comment]
So should proceed with `clickquestionSaveForQuestion1` and `clickQuestionEditForQuestion1`  ?

**Comment by chowyb** [comment]
@sujeet14108 yep
