### ISSUE TITLE
Java problem : account cannot be resolved to a variable 

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6332]
Suddenly i am facing this java problem. I don't know what's wrong . 

![screenshot 42](https://cloud.githubusercontent.com/assets/12005551/21860153/5e754ff8-d855-11e6-82d0-a5a51db3f4ad.png)

**Comment by xpdavid** [comment]
Seems like dependency issue. Try `./gradlew resetEclipseDeps` (`gradlew.bat resetEclipseDeps` on Windows) ?

**Comment by AnaghHegde** [comment]
@xpdavid No luck, still same problem.

**Comment by chowyb** [comment]
This is caused by Eclipse's validation, which should be fixed using [this answer](http://stackoverflow.com/a/2268714) by disabling the validation. The .jsp files actually contain valid code, but the default validation of Eclipse thinks otherwise.

**Comment by wkurniawan07** [comment]
@AnaghHegde have you tried refreshing the project folder?

**Comment by AnaghHegde** [comment]
@chowyb no use,i did that earlier only.

@wkurniawan07 i closed the project and then reopened the project.Still no luck.

**Comment by damithc** [comment]
@AnaghHegde use git to check if your code matches our master branch. Discard changes, if any. If that doesn't work, may be try to do a fresh set up just to figure out what went wrong?

**Comment by AnaghHegde** [comment]
@damithc ok i will try to figure out what went wrong. Fresh start in the sense from the scratch? right.

**Comment by wkurniawan07** [comment]
> i closed the project and then reopened the project

@AnaghHegde closing and reopening the project is not the same as refreshing.

**Comment by AnaghHegde** [comment]
@wkurniawan07 what i meant was re importing the project again to the workspace.

**Comment by wkurniawan07** [comment]
@AnaghHegde JSP files are not validated. Do refer to our setting up guide: ["We prefer not to use the HTML/JSP syntax validator provided by Eclipse"](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md#step-4-set-up-eclipse-ide). We have a [good reason for it](http://stackoverflow.com/questions/2268153/somevariable-cannot-be-resolved-error-indicated-in-eclipse-for-an-included-jsp/2268714#2268714).
